swagger: "2.0"

definations:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "User Status"
    xml:
      name: "User"
  Players:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "Player UUID"
      lastname:
        type: "string"
        description: "player last name"
      firstname:
        type: "string"
        description: "player first name"
      age:
        type: "integer"
        format: "int32"
        description: "Player age"
      birth:
        type: "string"
        description: "player birth date"
      achivement:
        type: "object"
      team:
        type: "object"
        scheme:
          $ref: "#/definitions/Team"

  Team:
    type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
          description: "Player UUID"
        teamName:
          type: "string"
          description: "player last name"
        address:
          type: "string"
          description: "player first name"
        teamOwner:
          type: "object"